spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3307/liutech?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver